export const ActionTypes = {
  ////// Fetch products //////
  PRODUCT_LIST_REQUEST: "PRODUCT_LIST_REQUEST",
  PRODUCT_LIST_SUCCESS: "PRODUCT_LIST_SUCCESS",
  PRODUCT_LIST_FAIL: "PRODUCT_LIST_FAIL",

  ////// Fetch single product //////
  PRODUCT_DETAIL_REQUEST: "PRODUCT_DETAIL_REQUEST",
  PRODUCT_DETAIL_SUCCESS: "PRODUCT_DETAIL_SUCCESS",
  PRODUCT_DETAIL_FAIL: "PRODUCT_DETAIL_FAIL",
};

////////////// Update Product ////////////

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";
export const PRODUCT_UPDATE_RESET = "PRODUCT_UPDATE_RESET";

////////////// Add Product ////////////

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";
export const CREATE_PRODUCT_RESET = "CREATE_PRODUCT_RESET";

//////////////// Infinite Scroll Product ////////////////

export const INFINITE_SCROLL_PRODUCT_REQUEST =
  "INFINITE_SCROLL_PRODUCT_REQUEST";
export const INFINITE_SCROLL_PRODUCT_SUCCESS =
  "INFINITE_SCROLL_PRODUCT_SUCCESS";
export const INFINITE_SCROLL_PRODUCT_FAIL = "INFINITE_SCROLL_PRODUCT_FAIL";
export const INFINITE_SCROLL_PRODUCT_RESET = "INFINITE_SCROLL_PRODUCT_RESET";
export const INFINITE_SCROLL_PRODUCT__PAGE_SUCCESS =
  "INFINITE_SCROLL_PRODUCT__PAGE_SUCCESS";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";

//////////////// Product Rating ////////////////

export const CREATE_PRODUCT_RATING_REQUEST = "CREATE_PRODUCT_RATING_REQUEST";
export const CREATE_PRODUCT_RATING_SUCCESS = "CREATE_PRODUCT_RATING_SUCCESS";
export const CREATE_PRODUCT_RATING_FAIL = "CREATE_PRODUCT_RATING_FAIL";
export const ADD_RATING = "ADD_RATING";

//////////////// Average Product Rating ////////////////

export const AVERAGE_PRODUCT_RATING_REQUEST = "AVERAGE_PRODUCT_RATING_REQUEST";
export const AVERAGE_PRODUCT_RATING_SUCCESS = "AVERAGE_PRODUCT_RATING_SUCCESS";
export const AVERAGE_PRODUCT_RATING_FAIL = "AVERAGE_PRODUCT_RATING_FAIL";

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";

////////////// recomended product //////////////

export const RECOMMENDED_PRODUCT_REQUEST = "RECOMMENDED_PRODUCT_REQUEST";
export const RECOMMENDED_PRODUCT_SUCCESS = "RECOMMENDED_PRODUCT_SUCCESS";
export const RECOMMENDED_PRODUCT_FAIL = "RECOMMENDED_PRODUCT_FAIL";
export const RECOMMENDED_PRODUCT_PUSH = "RECOMMENDED_PRODUCT_PUSH";
